"""
Backend Service - Alert Notification Microservice

This service consumes trading alerts from Kafka and sends push notifications
to mobile devices via Firebase Cloud Messaging (FCM).

Input: Kafka topic 'alert' with trading alert data
Output: Firebase Cloud Messaging notifications to subscribed users
"""
import firebase_admin
from firebase_admin import credentials
from kafka import KafkaConsumer
import json
from pathlib import Path

from send_message import send_data_message
import logging

# Service configuration
MICROSERVICE_NAME = "backend"

# Ensure logs directory exists
log_dir = Path("../logs")
log_dir.mkdir(parents=True, exist_ok=True)

# Configure logging for production
# Using 'a' (append) mode instead of 'w' to preserve logs across restarts
logging.basicConfig(
    level=logging.INFO,
    filename=f"../logs/{MICROSERVICE_NAME}.log",
    filemode="a",
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

logger = logging.getLogger(MICROSERVICE_NAME)
logger.info(f"Starting {MICROSERVICE_NAME} - Initializing Firebase and Kafka consumer")

# ============================================================================
# Firebase Initialization
# ============================================================================
# Initialize Firebase Admin SDK with service account credentials
# This enables sending push notifications via Firebase Cloud Messaging
try:
    cred_path = "firebase-admin-key.json"
    if not Path(cred_path).exists():
        logger.error(f"Firebase credentials file not found: {cred_path}")
        raise FileNotFoundError(f"Firebase credentials file not found: {cred_path}")
    
    cred = credentials.Certificate(cred_path)
    firebase_admin.initialize_app(cred)
    logger.info("Firebase Admin SDK initialized successfully")
except Exception as e:
    logger.error(f"Failed to initialize Firebase: {str(e)}", exc_info=True)
    raise

# ============================================================================
# Kafka Consumer Configuration
# ============================================================================
# Consume trading alerts from Kafka topic 'alert'
# These alerts are generated by the decision service when significant
# market movements are predicted
logger.info("Configuring Kafka consumer for topic 'alert'")
try:
    consumer = KafkaConsumer(
        "alert",
        bootstrap_servers="localhost:9092",  # Kafka broker address
        group_id="math-group",  # Consumer group ID for load balancing
        auto_offset_reset="earliest",  # Start from beginning if no offset exists
        enable_auto_commit=True,  # Automatically commit offsets
        value_deserializer=lambda v: json.loads(v.decode("utf-8"))  # Deserialize JSON messages
    )
    logger.info("Kafka consumer configured successfully")
except Exception as e:
    logger.error(f"Failed to configure Kafka consumer: {str(e)}", exc_info=True)
    raise

# ============================================================================
# Main Processing Loop
# ============================================================================
# Continuously consume alerts and send push notifications
logger.info("Starting alert processing loop - waiting for messages...")
try:
    for msg in consumer:
        data = msg.value
        logger.info(f"Received alert message: {json.dumps(data, indent=2)}")
        
        try:
            # Send push notification via Firebase Cloud Messaging
            res = send_data_message(data)
            logger.info(f"Alert notification sent successfully. Message ID: {res}")
            print(f"Alert sent: {res}")
        except Exception as e:
            logger.error(
                f"Failed to send alert notification: {str(e)} | "
                f"Alert data: {json.dumps(data)}",
                exc_info=True
            )
            # Continue processing other messages even if one fails
            continue
except KeyboardInterrupt:
    logger.info("Alert processing interrupted by user")
except Exception as e:
    logger.error(f"Fatal error in alert processing loop: {str(e)}", exc_info=True)
    raise
finally:
    if consumer:
        consumer.close()
        logger.info("Kafka consumer closed")
    